export const USER_STATE = {
    forgetPasswordState: { sendResetPasswordLinkSuccess: false, sendResetPasswordLinkError: false, emailId: "" },
    loginState: {
    error: { message: "", code: "" },
    isFailed: false,
    userData: {accessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNUQ0QkMyQzk5ODNCRTlGRjQ0OENGNjQwRDQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJCdFBrYnBFSFBGMUx3c21ZTy1uX1JJejJRTlEifQ.eyJuYmYiOjE1NTc3NDg1NDAsImV4cCI6MTU2MDM0MDU0MCwiaXNzIjoiaHR0cHM6Ly9jaHFhLW9hdXRoLWFwaS5jb3Jlb2Zsb3dzYW5kYm94LmNvbSIsImF1ZCI6WyJodHRwczovL2NocWEtb2F1dGgtYXBpLmNvcmVvZmxvd3NhbmRib3guY29tL3Jlc291cmNlcyIsImFwaTEiXSwiY2xpZW50X2lkIjoicm9jbGllbnQiLCJzdWIiOiJKb2huLldpbGxpYW1AbWFpbGluYXRvci5jb20iLCJhdXRoX3RpbWUiOjE1NTc3NDg1NDAsImlkcCI6ImxvY2FsIiwidXNlcm5hbWUiOiJKb2huLldpbGxpYW1AbWFpbGluYXRvci5jb20iLCJlbWFpbCI6IkpvaG4uV2lsbGlhbUBtYWlsaW5hdG9yLmNvbSIsInVzZXJpZCI6IjI4IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIklzRXVsYVVwZGF0ZWQiOiJUcnVlIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaTEiXSwiYW1yIjpbInBhc3N3b3JkIl19.iWYFrkvjJD8DhHjSQO5H4j6gQ20YJdehf2hqeaj553nHv4gX_8Tw5_tv1SW9a8CU0_xWc996rOJGnyS9vYRZ8l4keZ1oPSTMu95F-jNQ-xODfvdy_PSsK-UgJKeP70rrc59ns-udZLy0x2qkqiy0h70cHckxyg7nM8HadSrulpe1OiokVo-C55JgN2ni6kJFB7BbSMnqSJcmihQnFZHE8s4ys5Yoi1AWBvrKrzAfa5QN4kbuVV0P5awmgqKLGbrV6jNOTixzLM2vKOABu9Fj38-9p3STjJCNQ5HfaxUWHDC3TLNnpYlbZ2gr3DjJjW_VB81KvXbjKb-2q1FWWPwiJg"},
    logoutState: {
      error: { message: "", code: "" },
      loading: false,
      userData: {}
    },
    navigateToLoginReducer: { screen: "LOGIN_SCREEN" },
    resetPasswordState: {
      emailId: "",
      getEmailIdError: false,
      getEmailIdSuccess: false,
      patientId: null,
      resetPasswordError: false,
      resetPasswordLinkStatus: "",
      resetPasswordStatus: false,
      resetPasswordSuccess: false,
      token: "",
      userId: null
    },
    userAgreementState: {
      emailId: "John.William@mailinator.com",
      eulaContent: "<!DOCTYPE html><html lang='en'><head><meta charset",
      getEulaContentStatus: 400,
      isEulaUpdated: false
    },
    userState: {
      authData: { access_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…xUWHDC3TLNnpYlbZ2gr3DjJjW_VB81KvXbjKb-2q1FWWPwiJg", expires_in: 2592000, token_type: "Bearer" },
      autoLogoutTime: 1800000,
      careTeamId: 3,
      emailId: "john.william@mailinator.com",
      getPatientImageStatus: 0,
      impersinated: false,
      individualList: [],
      isUserMapped: true,
      lastViewedUserId: 1083,
      lastViewedUserType: "I",
      onBoardRelationShip: null,
      onBoardUserId: 0,
      patientId: 0,
      patientImage: {},
      patientName: {},
      relationshipName: "CareTeam",
      roles: {
        "Assign Service Providers to open_service_request": { Update: true, Read: true },
        "Async_Messages": { Create: true, Update: true, Read: true },
        "Bulk_invitation": { Create: true, Update: true, Read: true },
        "CareTeam_Settings": { Create: true, Read: true, Update: true, Delete: true },
        "Clinical Conditions": { Create: true, Update: true, Read: true, Delete: true },
        "Dashboard": { Create: true, Update: true, Read: true },
        "Geo_Map": { Read: true },
        "Languages Spoken": { Create: true, Update: true, Read: true, Delete: true },
        "Manage_Connections": { Create: true, Update: true, Read: true, Delete: true },
        "Notifications": { Read: true },
        "Payment": { Read: true },
        "Payment_Processing": { Create: true, Update: true, Read: true, Delete: true },
        "Profile": { Create: true, Update: true, Read: true, Delete: true },
        "Search": { Create: true, Update: true, Read: true, Delete: true },
        "Service_Provider_Standby": { Read: true },
        "Service_Providers(Hired/Invited)": { Create: true, Update: true, Read: true, Delete: true },
        "Service_Request": { Create: true, Update: true, Read: true, Delete: true },
        "Telehealth": { Create: true, Update: true, Read: true },
        "Users": { Create: true, Update: true, Read: true, Delete: true },
        "Visit_History": { Create: true, Update: true, Read: true, Delete: true },
        "Visit_Processing": { Create: true, Update: true, Read: true, Delete: true }
      },
      selectedPatientInfo: {},
      userEmail: "john.william@mailinator.com",
      userId: 28,
      userInfo: {
        careTeamId: 3,
        coreoHomeUserId: 28,
        email: "john.william@mailinator.com",
        emailId: "john.william@mailinator.com",
        isUserMapped: true,
        lastViewedUserId: 1083,
        lastViewedUserType: "I",
        onBoardRelationShip: null,
        onBoardUserId: 0,
        patientId: 0,
        relationshipName: "CareTeam",
        userId: 28,
        userType: "CT"
      },
      userType: "CT"
    }
  },
  userState: {
    authData: { access_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…xUWHDC3TLNnpYlbZ2gr3DjJjW_VB81KvXbjKb-2q1FWWPwiJg", expires_in: 2592000, token_type: "Bearer" },
    autoLogoutTime: 1800000,
    careTeamId: 3,
    emailId: "john.william@mailinator.com",
    getPatientImageStatus: 0,
    impersinated: false,
    individualList: [],
    isUserMapped: true,
    lastViewedUserId: 1083,
    lastViewedUserType: "I",
    onBoardRelationShip: null,
    onBoardUserId: 0,
    patientId: 0,
    patientImage: {},
    patientName: {},
    relationshipName: "CareTeam",
    roles: {
      "Assign Service Providers to open_service_request": { Update: true, Read: true },
      "Async_Messages": { Create: true, Update: true, Read: true },
      "Bulk_invitation": { Create: true, Update: true, Read: true },
      "CareTeam_Settings": { Create: true, Read: true, Update: true, Delete: true },
      "Clinical Conditions": { Create: true, Update: true, Read: true, Delete: true },
      "Dashboard": { Create: true, Update: true, Read: true },
      "Geo_Map": { Read: true },
      "Languages Spoken": { Create: true, Update: true, Read: true, Delete: true },
      "Manage_Connections": { Create: true, Update: true, Read: true, Delete: true },
      "Notifications": { Read: true },
      "Payment": { Read: true },
      "Payment_Processing": { Create: true, Update: true, Read: true, Delete: true },
      "Profile": { Create: true, Update: true, Read: true, Delete: true },
      "Search": { Create: true, Update: true, Read: true, Delete: true },
      "Service_Provider_Standby": { Read: true },
      "Service_Providers(Hired/Invited)": { Create: true, Update: true, Read: true, Delete: true },
      "Service_Request": { Create: true, Update: true, Read: true, Delete: true },
      "Telehealth": { Create: true, Update: true, Read: true },
      "Users": { Create: true, Update: true, Read: true, Delete: true },
      "Visit_History": { Create: true, Update: true, Read: true, Delete: true },
      "Visit_Processing": { Create: true, Update: true, Read: true, Delete: true }
    },
    selectedPatientInfo: {},
    userEmail: "john.william@mailinator.com",
    userId: 28,
    userInfo: {
      careTeamId: 3,
      coreoHomeUserId: 28,
      email: "john.william@mailinator.com",
      emailId: "john.william@mailinator.com",
      isUserMapped: true,
      lastViewedUserId: 1083,
      lastViewedUserType: "I",
      onBoardRelationShip: null,
      onBoardUserId: 0,
      patientId: 0,
      relationshipName: "CareTeam",
      userId: 28,
      userType: "CT"
    },
    userType: "CT"
  }
}