export let authState = [{
    forgetPasswordState: { sendResetPasswordLinkSuccess: false, sendResetPasswordLinkError: false, emailId: "" },
    loginState: {
        error: { message: "", code: "" },
        isFailed: false,
        userData: { accessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ" }
    },
    logoutState: {
        deviceToken: "f_krPDlhwak:APA91bH85McmbdDM5Ekdjoo68iu3AW9Pl6fDDH5RVJguSjvROp1WjmqH-THotXBDU86XQYAUOvBRB9Ubt5dphccYO_JjGfaEBATrXWpizE8fdO9gqoBMLWiQPZmptbjxcVu6zk67IyV4",
        error: { message: "", code: "" },
        loading: false,
        userData: {}
    },
    navigateToLoginReducer: { screen: "LOGIN_SCREEN" },
    resetPasswordState: {
        emailId: "",
        getEmailIdError: false,
        getEmailIdSuccess: false,
        patientId: null,
        resetPasswordError: false,
        resetPasswordLinkStatus: "",
        resetPasswordStatus: false,
        resetPasswordSuccess: false,
        token: "",
        userId: null
    },
    userAgreementState: {
        emailId: "smith@mailinator.com",
        eulaContent: "<!DOCTYPE html><html lang='en'><head><meta charset",
        getEulaContentStatus: 400,
        isEulaUpdated: false
    },
    userState: {
        authData: { access_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ", expires_in: 2592000, token_type: "Bearer" },
        autoLogoutTime: 1800000,
        careTeamId: 0,
        emailId: "smith@mailinator.com",
        getPatientImageStatus: 200,
        impersinated: false,
        individualList: [],
        isUserMapped: true,
        lastViewedUserId: 1096,
        lastViewedUserType: "I",
        onBoardRelationShip: null,
        onBoardUserId: 0,
        patientId: 1096,
        patientImage: { image: null },
        patientName: {
            addresses: [
                {
                    addressId: 272,
                    addressTypeId: null,
                    city: "Los Angeles",
                    isActive: true,
                    isPrimaryAddress: true,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 5, name: "California" },
                    stateId: 0,
                    stateName: null,
                    street: "3135  Doctors Drive",
                    zip: 90017
                },
                {
                    addressId: 274,
                    addressTypeId: "Office",
                    city: "St. Louis",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 25, name: "Missouri" },
                    stateId: 0,
                    stateName: null,
                    street: "510 Maryville University 510Maryville UniversityMaryville University",
                    zip: 63141
                },
                {
                    addressId: 279,
                    addressTypeId: "",
                    city: "WAIMANALO",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 11, name: "Hawaii" },
                    stateId: 0,
                    stateName: null,
                    street: "1271 Ranugad Street",
                    zip: 96795
                },
                {
                    addressId: 282,
                    addressTypeId: "Office",
                    city: "Framingham",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 21, name: "Massachusetts" },
                    stateId: 0,
                    stateName: null,
                    street: "643  C Street",
                    zip: 1702
                }
            ],
            age: 27,
            description: null,
            firstName: "steve",
            gender: { id: 6, genderName: "Male" },
            isActive: false,
            lastName: "smith",
            patientId: 1096,
            phoneNumber: "098-765-4465",
            rowversionId: null
        },
        relationshipName: "Self",
        roles: {

            Async_Messages: { Create: true, Update: true, Read: true },
            Dashboard: { Read: true },
            Login: { Create: true, Update: true, Read: true },
            Manage_Connections: { Create: true, Update: true, Read: true, Delete: true },
            Payment_Processing: { Create: true, Update: true, Read: true, Delete: true },
            Profile: { Create: true, Update: true, Read: true, Delete: true },
            Search: { Create: true, Update: true, Read: true, Delete: true },
            Service_Request: { Create: true, Update: true, Read: true, Delete: true },
            Telehealth: { Create: true, Update: true, Read: true },
            Visit_History: { Read: true },
            Visit_Processing: { Read: true }
        },
        selectedPatientInfo: {},
        userEmail: "smith@mailinator.com",
        userId: 362,
        userImage: null,
        userInfo: {
            careTeamId: 0,
            coreoHomeUserId: 362,
            email: "smith@mailinator.com",
            emailId: "smith@mailinator.com",
            isUserMapped: true,
            lastViewedUserId: 1096,
            lastViewedUserType: "I",
            onBoardRelationShip: null,
            onBoardUserId: 0,
            patientId: 1096,
            relationshipName: "Self",
            userId: 362,
            userType: "I"
        },
        userType: "I"
    }
},
{
    forgetPasswordState: { sendResetPasswordLinkSuccess: false, sendResetPasswordLinkError: false, emailId: "" },
    loginState: {
        error: { message: "", code: "" },
        isFailed: false,
        userData: { accessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ" }
    },
    logoutState: {
        deviceToken: "f_krPDlhwak:APA91bH85McmbdDM5Ekdjoo68iu3AW9Pl6fDDH5RVJguSjvROp1WjmqH-THotXBDU86XQYAUOvBRB9Ubt5dphccYO_JjGfaEBATrXWpizE8fdO9gqoBMLWiQPZmptbjxcVu6zk67IyV4",
        error: { message: "", code: "" },
        loading: false,
        userData: {}
    },
    navigateToLoginReducer: { screen: "LOGIN_SCREEN" },
    resetPasswordState: {
        emailId: "",
        getEmailIdError: false,
        getEmailIdSuccess: false,
        patientId: null,
        resetPasswordError: false,
        resetPasswordLinkStatus: "",
        resetPasswordStatus: false,
        resetPasswordSuccess: false,
        token: "",
        userId: null
    },
    userAgreementState: {
        emailId: "smith@mailinator.com",
        eulaContent: "<!DOCTYPE html><html lang='en'><head><meta charset",
        getEulaContentStatus: 400,
        isEulaUpdated: false
    },
    userState: {
        authData: { access_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ", expires_in: 2592000, token_type: "Bearer" },
        autoLogoutTime: 1800000,
        careTeamId: 0,
        emailId: "smith@mailinator.com",
        getPatientImageStatus: 200,
        impersinated: false,
        individualList: [],
        isUserMapped: true,
        lastViewedUserId: 1096,
        lastViewedUserType: "G",
        onBoardRelationShip: null,
        onBoardUserId: 0,
        patientId: 1096,
        patientImage: { image: null },
        patientName: {
            addresses: [
                {
                    addressId: 272,
                    addressTypeId: null,
                    city: "Los Angeles",
                    isActive: true,
                    isPrimaryAddress: true,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 5, name: "California" },
                    stateId: 0,
                    stateName: null,
                    street: "3135  Doctors Drive",
                    zip: 90017
                },
                {
                    addressId: 274,
                    addressTypeId: "Office",
                    city: "St. Louis",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 25, name: "Missouri" },
                    stateId: 0,
                    stateName: null,
                    street: "510 Maryville University 510Maryville UniversityMaryville University",
                    zip: 63141
                },
                {
                    addressId: 279,
                    addressTypeId: "",
                    city: "WAIMANALO",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 11, name: "Hawaii" },
                    stateId: 0,
                    stateName: null,
                    street: "1271 Ranugad Street",
                    zip: 96795
                },
                {
                    addressId: 282,
                    addressTypeId: "Office",
                    city: "Framingham",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 21, name: "Massachusetts" },
                    stateId: 0,
                    stateName: null,
                    street: "643  C Street",
                    zip: 1702
                }
            ],
            age: 27,
            description: null,
            firstName: "steve",
            gender: { id: 6, genderName: "Male" },
            isActive: false,
            lastName: "smith",
            patientId: 1096,
            phoneNumber: "098-765-4465",
            rowversionId: null
        },
        relationshipName: "Self",
        roles: {

            Async_Messages: { Create: true, Update: true, Read: true },
            Dashboard: { Read: true },
            Login: { Create: true, Update: true, Read: true },
            Manage_Connections: { Create: true, Update: true, Read: true, Delete: true },
            Payment_Processing: { Create: true, Update: true, Read: true, Delete: true },
            Profile: { Create: true, Update: true, Read: true, Delete: true },
            Search: { Create: true, Update: true, Read: true, Delete: true },
            Service_Request: { Create: true, Update: true, Read: true, Delete: true },
            Telehealth: { Create: true, Update: true, Read: true },
            Visit_History: { Read: true },
            Visit_Processing: { Read: true }
        },
        selectedPatientInfo: {},
        userEmail: "smith@mailinator.com",
        userId: 362,
        userImage: 'sampleUserImage',
        userInfo: {
            careTeamId: 0,
            coreoHomeUserId: 362,
            email: "smith@mailinator.com",
            emailId: "smith@mailinator.com",
            isUserMapped: true,
            lastViewedUserId: 1096,
            lastViewedUserType: "G",
            onBoardRelationShip: null,
            onBoardUserId: 0,
            patientId: 1096,
            relationshipName: "Self",
            userId: 362,
            userType: "G"
        },
        userType: "G"
    }
},

{
    forgetPasswordState: { sendResetPasswordLinkSuccess: false, sendResetPasswordLinkError: false, emailId: "" },
    loginState: {
        error: { message: "", code: "" },
        isFailed: false,
        userData: { accessToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ" }
    },
    logoutState: {
        deviceToken: "f_krPDlhwak:APA91bH85McmbdDM5Ekdjoo68iu3AW9Pl6fDDH5RVJguSjvROp1WjmqH-THotXBDU86XQYAUOvBRB9Ubt5dphccYO_JjGfaEBATrXWpizE8fdO9gqoBMLWiQPZmptbjxcVu6zk67IyV4",
        error: { message: "", code: "" },
        loading: false,
        userData: {}
    },
    navigateToLoginReducer: { screen: "LOGIN_SCREEN" },
    resetPasswordState: {
        emailId: "",
        getEmailIdError: false,
        getEmailIdSuccess: false,
        patientId: 123,
        resetPasswordError: false,
        resetPasswordLinkStatus: "",
        resetPasswordStatus: false,
        resetPasswordSuccess: false,
        token: "",
        userId: null
    },
    userAgreementState: {
        emailId: "smith@mailinator.com",
        eulaContent: "<!DOCTYPE html><html lang='en'><head><meta charset",
        getEulaContentStatus: 400,
        isEulaUpdated: false
    },
    userState: {
        authData: { access_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNU…75rlUZklm2d7ZhilJW26SQnG3oWLqMgPZPN1w7v0q6RiN9PdQ", expires_in: 2592000, token_type: "Bearer" },
        autoLogoutTime: 1800000,
        careTeamId: 0,
        emailId: "smith@mailinator.com",
        getPatientImageStatus: 200,
        impersinated: false,
        individualList: [],
        isUserMapped: true,
        lastViewedUserId: 1096,
        lastViewedUserType: "CT",
        onBoardRelationShip: null,
        onBoardUserId: 0,
        patientId: 1096,
        patientImage: { image: null },
        patientName: {
            addresses: [
                {
                    addressId: 272,
                    addressTypeId: null,
                    city: "Los Angeles",
                    isActive: true,
                    isPrimaryAddress: true,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 5, name: "California" },
                    stateId: 0,
                    stateName: null,
                    street: "3135  Doctors Drive",
                    zip: 90017
                },
                {
                    addressId: 274,
                    addressTypeId: "Office",
                    city: "St. Louis",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 25, name: "Missouri" },
                    stateId: 0,
                    stateName: null,
                    street: "510 Maryville University 510Maryville UniversityMaryville University",
                    zip: 63141
                },
                {
                    addressId: 279,
                    addressTypeId: "",
                    city: "WAIMANALO",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 11, name: "Hawaii" },
                    stateId: 0,
                    stateName: null,
                    street: "1271 Ranugad Street",
                    zip: 96795
                },
                {
                    addressId: 282,
                    addressTypeId: "Office",
                    city: "Framingham",
                    isActive: true,
                    isPrimaryAddress: false,
                    patientId: 1096,
                    rowVersionId: null,
                    state: { id: 21, name: "Massachusetts" },
                    stateId: 0,
                    stateName: null,
                    street: "643  C Street",
                    zip: 1702
                }
            ],
            age: 27,
            description: null,
            firstName: "steve",
            gender: { id: 6, genderName: "Male" },
            isActive: false,
            lastName: "smith",
            patientId: 1096,
            phoneNumber: "098-765-4465",
            rowversionId: null
        },
        relationshipName: "Self",
        roles: {

            Async_Messages: { Create: true, Update: true, Read: true },
            Dashboard: { Read: true },
            Login: { Create: true, Update: true, Read: true },
            Manage_Connections: { Create: true, Update: true, Read: true, Delete: true },
            Payment_Processing: { Create: true, Update: true, Read: true, Delete: true },
            Profile: { Create: true, Update: true, Read: true, Delete: true },
            Search: { Create: true, Update: true, Read: true, Delete: true },
            Service_Request: { Create: true, Update: true, Read: true, Delete: true },
            Telehealth: { Create: true, Update: true, Read: true },
            Visit_History: { Read: true },
            Visit_Processing: { Read: true }
        },
        selectedPatientInfo: {userType: 'I'},
        userEmail: "smith@mailinator.com",
        userId: 362,
        userImage: 'sampleUserImage',
        userInfo: {
            careTeamId: 0,
            coreoHomeUserId: 362,
            email: "smith@mailinator.com",
            emailId: "smith@mailinator.com",
            isUserMapped: true,
            lastViewedUserId: 1096,
            lastViewedUserType: "CT",
            onBoardRelationShip: null,
            onBoardUserId: 0,
            patientId: 1096,
            relationshipName: "Self",
            userId: 362,
            userType: "CT"
        },
        userType: "CT"
    }
}]

export let profileState = {
    addresses: [
        {
            addressId: 272,
            addressTypeId: null,
            city: "Los Angeles",
            isActive: true,
            isPrimaryAddress: true,
            patientId: 1096,
            rowVersionId: null,
            state: { id: 5, name: "California" },
            stateId: 0,
            stateName: null,
            street: "3135  Doctors Drive",
            zip: 90017
        },
        {
            addressId: 274,
            addressTypeId: "Office",
            city: "St. Louis",
            isActive: true,
            isPrimaryAddress: false,
            patientId: 1096,
            rowVersionId: null,
            state: { id: 25, name: "Missouri" },
            stateId: 0,
            stateName: null,
            street: "510 Maryville University 510Maryville UniversityMaryville University",
            zip: 63141
        },
        {
            addressId: 279,
            addressTypeId: "",
            city: "WAIMANALO",
            isActive: true,
            isPrimaryAddress: false,
            patientId: 1096,
            rowVersionId: null,
            state: { id: 11, name: "Hawaii" },
            stateId: 0,
            stateName: null,
            street: "1271 Ranugad Street",
            zip: 96795
        },
        {
            addressId: 282,
            addressTypeId: "Office",
            city: "Framingham",
            isActive: true,
            isPrimaryAddress: false,
            patientId: 1096,
            rowVersionId: null,
            state: { id: 21, name: "Massachusetts" },
            stateId: 0,
            stateName: null,
            street: "643  C Street",
            zip: 1702
        }
    ],
    age: 27,
    description: null,
    firstName: "steve",
    gender: { id: 6, genderName: "Male" },
    isActive: false,
    lastName: "smith",
    patientId: 1096,
    phoneNumber: "098-765-4465",
    rowversionId: null
}