export let menuState = [{
    aboutUsState: {
        buildVersion: "V1.1.2 Build# 1004",
        contentCode: "<!DOCTYPE html><html lang='en'><head> <meta charset='UTF-8'> <title>Title</title> <style>html, body{padding: 0; margin: 0; font-family: 'Open Sans'; color: #444444; font-size: 12px;}.AboutUsWidget{display: block; position: relative; width: 100%;}.AboutUsLogoWidget{display: flex; flex-direction: row; justify-content: space-between; position: relative; padding: 30px 15px; border-bottom: 1px solid #d7d7d7;}.AboutUsLogo, .AboutUsVersion{display: block; position: relative; width: 50%;}.AboutUsLogo{height: 20px;}.AboutUsLogo img{display: block; height: 100%;}.AboutUsVersion{text-align: right;}.AboutUsContentWidget{padding: 30px 15px;}.AboutUsContent{margin-bottom: 30px;}.AboutUsContent h4{margin: 0; color: #1e3d5c; font-size: 16px;}.AboutUsContent p{}.AboutUsContent a{display: block; text-decoration: none; color: #1e3d5c; padding: 10px 0; border-bottom: 1px solid #d7d7d7;}.AboutUsContent a:last-child{border: 0;}.AboutUsContent a:hover{color: #3c1053;}</style></head><body><section class='AboutUsWidget'> <div class='AboutUsLogoWidget'> <span class='AboutUsLogo'><img src='../assets/img/logo/CoreoHomeGray.png'></span> <span class='AboutUsVersion'>Version 1.0</span> </div><div class='AboutUsContentWidget'><div class='AboutUsContent'> <h4>Navvis Healthcare</h4> <p>At Navvis we all come to work with one thing in mind. How can we take the good healthcare that we have and turn it into the great healthcare we all deserve? <br><br>There is nothing that gets us more excited than tackling big and complicated problems like this. It’s core to our DNA. After working with healthcare leaders for more than 20 years, we have learned that the real underlying problem they face is growth and diversification. <br><br>The opportunities to solve this problem are often hidden because of a paradox they live with, choosing between volume-based growth or value-based performance. Many believe they must make a choice between volume OR value to be successful.</p></div><div class='AboutUsContent'> <h4>Reach out to us at</h4><a href=" / ">www.navvishealthcare.com</a> </div></div></section></body></html>",
        loadingStatus: 200
    },
    paymentState: { CardList: null, paymentStatus: "IN_PROGRESS" }
},
{
    aboutUsState: {
        buildVersion: "V1.1.2 Build# 1004",
        contentCode: "<!DOCTYPE html><html lang='en'><head> <meta charset='UTF-8'> <title>Title</title> <style>html, body{padding: 0; margin: 0; font-family: 'Open Sans'; color: #444444; font-size: 12px;}.AboutUsWidget{display: block; position: relative; width: 100%;}.AboutUsLogoWidget{display: flex; flex-direction: row; justify-content: space-between; position: relative; padding: 30px 15px; border-bottom: 1px solid #d7d7d7;}.AboutUsLogo, .AboutUsVersion{display: block; position: relative; width: 50%;}.AboutUsLogo{height: 20px;}.AboutUsLogo img{display: block; height: 100%;}.AboutUsVersion{text-align: right;}.AboutUsContentWidget{padding: 30px 15px;}.AboutUsContent{margin-bottom: 30px;}.AboutUsContent h4{margin: 0; color: #1e3d5c; font-size: 16px;}.AboutUsContent p{}.AboutUsContent a{display: block; text-decoration: none; color: #1e3d5c; padding: 10px 0; border-bottom: 1px solid #d7d7d7;}.AboutUsContent a:last-child{border: 0;}.AboutUsContent a:hover{color: #3c1053;}</style></head><body><section class='AboutUsWidget'> <div class='AboutUsLogoWidget'> <span class='AboutUsLogo'><img src='../assets/img/logo/CoreoHomeGray.png'></span> <span class='AboutUsVersion'>Version 1.0</span> </div><div class='AboutUsContentWidget'><div class='AboutUsContent'> <h4>Navvis Healthcare</h4> <p>At Navvis we all come to work with one thing in mind. How can we take the good healthcare that we have and turn it into the great healthcare we all deserve? <br><br>There is nothing that gets us more excited than tackling big and complicated problems like this. It’s core to our DNA. After working with healthcare leaders for more than 20 years, we have learned that the real underlying problem they face is growth and diversification. <br><br>The opportunities to solve this problem are often hidden because of a paradox they live with, choosing between volume-based growth or value-based performance. Many believe they must make a choice between volume OR value to be successful.</p></div><div class='AboutUsContent'> <h4>Reach out to us at</h4><a href=" / ">www.navvishealthcare.com</a> </div></div></section></body></html>",
        loadingStatus: 100
    },
    paymentState: { CardList: null, paymentStatus: "IN_PROGRESS" }
}]